In [58]:
import numpy as np

In [59]:
grid = np.zeros((5, 5)) #initializing grid of 5x5
gamma = 0.9 #discounting factor

In [60]:
for _ in range(1000): #1000 eps ~ infinity
    for i in range(5): #iterating over grid
        for j in range(5):
            v = 0 #value function initialized
            
            #taking care of special case, v = reward + Y*v[next state]
            if i == 0 and j == 1:
                v = 10 + gamma*grid[4][1]
            elif i == 0 and j == 3:
                v = 5 + gamma*grid[2][3]
            else:
                up = 0
                down = 0
                right = 0
                left = 0

                #this is a flag that saves us from going out of the grid
                if i > 0:
                    up = grid[i-1][j] 
                if i < 4:
                    down = grid[i+1][j]
                if j > 0:
                    left = grid[i][j-1]
                if j < 4:
                    right = grid[i][j+1]

                # if we have not gone out of the grid, then v is accordingly the new state
                # else we next state is that same state and v is accordingly
                if up != 0:
                    v += 0.25*(0 + gamma*up)
                else:
                    v += 0.25*(-1 + gamma*grid[i][j])

                if down != 0:
                    v += 0.25*(0 + gamma*down)
                else:
                    v += 0.25*(-1 + gamma*grid[i][j])

                if left != 0:
                    v += 0.25*(0 + gamma*left)
                else:
                    v += 0.25*(-1 + gamma*grid[i][j])

                if right != 0:
                    v += 0.25*(0 + gamma*right)
                else:
                    v += 0.25*(-1 + gamma*grid[i][j])

            grid[i][j] = v #putting the value into the grid

In [61]:
grid = np.round(grid, 1)
print(grid)

[[ 3.3  8.8  4.4  5.3  1.5]
 [ 1.5  3.   2.3  1.9  0.5]
 [ 0.1  0.7  0.7  0.4 -0.4]
 [-1.  -0.4 -0.4 -0.6 -1.2]
 [-1.9 -1.3 -1.2 -1.4 -2. ]]
