In [1]:
import numpy as np

In [2]:
grid = np.zeros((4, 4)) #initializing grid of 4x4
# temp grid is needed to store the value of v during one iteration v calcuation
# after each episode, the final value is stored in the main grid at the end
grid_temp = np.zeros((4, 4))
gamma = 1 #discounting factor (no discounting)
p = 0.25
r = -1

In [3]:
for _ in range(120): #120 eps ~ infinity
    for i in range(4): #iterating over grid
        for j in range(4):
            # handling the special case (left top corner and right bottom corner)
            if (i == 0 and j == 0) or (i == 3 and j == 3):
                continue
            else:
                up = None
                down = None
                right = None
                left = None

                #this is a flag that saves us from going out of the grid
                if i > 0:
                    up = grid_temp[i-1][j]
                if i < 3:
                    down = grid_temp[i+1][j]
                if j > 0:
                    left = grid_temp[i][j-1]
                if j < 3:
                    right = grid_temp[i][j+1]

                # v = reward + Y*v[next state]
                v = 0
                if up != None:
                    v += p*(r + gamma*up)
                else:
                    v += p*(r + gamma*grid_temp[i][j])

                if down != None:
                    v += p*(r + gamma*down)
                else:
                    v += p*(r + gamma*grid_temp[i][j])

                if left != None:
                    v += p*(r + gamma*left)
                else:
                    v += p*(r + gamma*grid_temp[i][j])

                if right != None:
                    v += p*(r + gamma*right)
                else:
                    v += p*(r + gamma*grid_temp[i][j])

                # here we put the final value of v calculated in this iteration 
                # and store it in the main grid for use in the next iteration
                grid[i][j] = v
    
    # here we update the temp grid so that the next iteration 
    # uses the final values of previous iteration
    grid_temp = grid.copy()
    
    # printing all iterations
    grid = np.round(grid, 1)
    print(grid)

[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[ 0.  -1.8 -2.  -2. ]
 [-1.8 -2.  -2.  -2. ]
 [-2.  -2.  -2.  -1.8]
 [-2.  -2.  -1.8  0. ]]
[[ 0.  -2.4 -2.9 -3. ]
 [-2.4 -2.9 -3.  -2.9]
 [-2.9 -3.  -2.9 -2.4]
 [-3.  -2.9 -2.4  0. ]]
[[ 0.  -3.1 -3.8 -4. ]
 [-3.1 -3.7 -3.9 -3.8]
 [-3.8 -3.9 -3.7 -3.1]
 [-4.  -3.8 -3.1  0. ]]
[[ 0.  -3.7 -4.7 -4.9]
 [-3.7 -4.5 -4.8 -4.7]
 [-4.7 -4.8 -4.5 -3.7]
 [-4.9 -4.7 -3.7  0. ]]
[[ 0.  -4.2 -5.5 -5.8]
 [-4.2 -5.2 -5.6 -5.5]
 [-5.5 -5.6 -5.2 -4.2]
 [-5.8 -5.5 -4.2  0. ]]
[[ 0.  -4.7 -6.3 -6.7]
 [-4.7 -5.9 -6.4 -6.3]
 [-6.3 -6.4 -5.9 -4.7]
 [-6.7 -6.3 -4.7  0. ]]
[[ 0.  -5.2 -7.  -7.5]
 [-5.2 -6.5 -7.1 -7. ]
 [-7.  -7.1 -6.5 -5.2]
 [-7.5 -7.  -5.2  0. ]]
[[ 0.  -5.7 -7.7 -8.2]
 [-5.7 -7.2 -7.8 -7.7]
 [-7.7 -7.8 -7.2 -5.7]
 [-8.2 -7.7 -5.7  0. ]]
[[ 0.  -6.1 -8.4 -9. ]
 [-6.1 -7.7 -8.4 -8.4]
 [-8.4 -8.4 -7.7 -6.1]
 [-9.  -8.4 -6.1  0. ]]
[[ 0.  -6.6 -9.  -9.7]
 [-6.6 -8.3 -9.  -9. ]
 [-9.  -9.  -8.3 -6.6]
 [-9.7 -9.  -6.6 

In [4]:
grid = np.round(grid, 1)
print(grid)

[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
