In [143]:
import numpy as np

In [144]:
grid = np.zeros((5, 5)) #initializing grid of 5x5
policyGrid = [['', '', '', '', ''], #initializing the policy grid of 5x5
              ['', '', '', '', ''], 
              ['', '', '', '', ''], 
              ['', '', '', '', ''], 
              ['', '', '', '', '']]
gamma = 0.9 #discounting factor

In [145]:
for _ in range(1000): #1000 eps ~ infinity
    for i in range(5): #iterating over grid
        for j in range(5):
            #As we need to find the optimal value and policy,
            #I take 4 values for 4 actions and 1 default and 
            # compare them at the last
            v = 0 
            v1 = 0
            v2 = 0
            v3 = 0
            v4 = 0
            
            #taking care of special case, v = reward + Y*v[next state]
            if i == 0 and j == 1:
                v = 10 + gamma*grid[4][1]
            elif i == 0 and j == 3:
                v = 5 + gamma*grid[2][3]
            else:
                up = 0
                down = 0
                right = 0
                left = 0

                #this is a flag that saves us from going out of the grid
                if i > 0:
                    up = grid[i-1][j]
                if i < 4:
                    down = grid[i+1][j]
                if j > 0:
                    left = grid[i][j-1]
                if j < 4:
                    right = grid[i][j+1]
                
                # if we have not gone out of the grid, then v is accordingly the new state
                # else we next state is that same state and v is accordingly
                if up != 0:
                    v1 = 0 + gamma*up
                else:
                    v1 = -1 + gamma*grid[i][j]

                if down != 0:
                    v2 = 0 + gamma*down
                else:
                    v2 = -1 + gamma*grid[i][j]

                if left != 0:
                    v3 = 0 + gamma*left
                else:
                    v3 = -1 + gamma*grid[i][j]

                if right != 0:
                    v4 = 0 + gamma*right
                else:
                    v4 = -1 + gamma*grid[i][j]
            
            #Comparing all values and getting the optimal one
            L = [v1, v2, v3, v4, v]
            temp = max(L)
            
            #Calculating the right arrows for optimal policy
            arrow = 'A' #set default A (= ALL) for the special case
            if temp == v1:
                arrow = '^'
            if temp == v2:
                arrow = 'V'
            if temp == v3:
                arrow = '<'
            if temp == v4:
                arrow = '>'
                
            grid[i][j] = temp #putting the value into the grid
            policyGrid[i][j] = arrow #putting the actions into policy grid

In [146]:
grid = np.round(grid, 1)
print(grid)
for a in range(len(policyGrid)):
    for b in range(len(policyGrid[0])):
        print(policyGrid[a][b], end = " ")
    print()

[[22.  24.4 22.  19.4 17.5]
 [19.8 22.  19.8 17.8 16. ]
 [17.8 19.8 17.8 16.  14.4]
 [16.  17.8 16.  14.4 13. ]
 [14.4 16.  14.4 13.  11.7]]
> A < A < 
> ^ < < < 
> ^ < < < 
> ^ < < < 
> ^ < < < 
